DROP TABLE IF  EXISTS hits_statistics CASCADE;

CREATE TABLE IF NOT EXISTS hits_statistics (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR(255) NOT NULL,
    ip VARCHAR(15) NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE
);